version: '3.8'

services:
  clientes-db:
    image: mysql:8
    container_name: clientes-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientes_db
    ports:
      - "3306:3306"
    volumes:
      - clientes_db_data:/var/lib/mysql

  clientes-backend:
    build: ./clientes-backend
    container_name: clientes-backend
    env_file:
      - ./clientes-backend/.env
    depends_on:
      - clientes-db
    ports:
      - "8001:8001"

  clientes-frontend:
    build: ./clientes-frontend
    container_name: clientes-frontend
    ports:
      - "5173:80"
    depends_on:
      - clientes-backend

volumes:
  clientes_db_data:
